# -*- coding: utf-8 -*-
"""Titanic_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/scratchpad/titanic-analysis.8b7cdead-d046-43b3-aec9-a088300ba4cf.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250424/auto/storage/goog4_request%26X-Goog-Date%3D20250424T180840Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3De5eed9929311737fea884083e75f86442b743ea45101380266ec37f3b66f27a88be0a81e0f7f80763151d59295698abe37e442990d9f9876dab6b0df6e0d26d67e4ec4c1ce9c2fbf72dc4b0585c03dbced5749bacb71fea8793902892bd8bd4e3525d6355f42ca94e4157cf7d5382d54f4d2ee45a3ebe90d7213e175b2af4238dc6c0f7818071e56391ecc02a544836b6b09c951d0f838d6683745512eb588bfc347e9a89e38550cab00a26108eff30957055633ebaeb795d3c125bc6d7c3506585c6a8e75451d943fd141c4d793c7280a94383afecc1cc8d11403a8a5fa7d8c9112696888ae89de6ae284692fbf304dbea63ce7c29c356b486880c21f13aaa9
"""

import kagglehub
yasserh_titanic_dataset_path = kagglehub.dataset_download('yasserh/titanic-dataset')

print('Data source import complete.')



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer

"""# Importing the dataset:"""

df=pd.read_csv("/kaggle/input/titanic-dataset/Titanic-Dataset.csv",index_col=0)

"""# Exploring the dataset:"""

df.head()

df.shape

df.info()

df.describe()

"""# Handling the missing values:"""

df.isnull().sum()

"""### Filling the missing value of Age column using median:"""

df['Age'].fillna(df['Age'].median(), inplace=True)

"""### Filling the missing value of Cabin column using most frequent:
-> because the Cabin column's datatype is object therefore we can use most_frequent method to fill the missing values.
"""

df['Cabin'].value_counts()

si=SimpleImputer(strategy='most_frequent')
df['Cabin'] = si.fit_transform(df[['Cabin']]).ravel()

"""### Filling the missing value of the Embarked columns:"""

df['Embarked'].value_counts()

df['Embarked']=si.fit_transform(df[['Embarked']]).ravel()

"""### Varifying the process:"""

df.isnull().sum()

"""# Splitting the cabin column:"""

df['Deck'] = df['Cabin'].str.extract(r'([A-Za-z])')  # Extract the letter part as Deck
df['Room'] = df['Cabin'].str.extract(r'(\d+)')      # Extract the number part as Room

df.head()

df.drop(columns=['Cabin'],inplace=True)

df.head()

df['Room']=df['Room'].astype('float')

"""# Converting categorical features into Numerical using encoding:"""

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df['Deck']=le.fit_transform(df['Deck'])

df['Embarked']=le.fit_transform(df['Embarked'])

df['Sex']=le.fit_transform(df['Sex'])

df.head()

"""# Normalizing and standardizing the Numerical features:

### Applying the normalization technique on the Age and fare columns:
"""

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

df['Normalized_Age']=scaler.fit_transform(df[['Age']])

df['Normalized_Fare'] = scaler.fit_transform(df[['Fare']])

df.head()

"""# visualizing the Outliers using boxplot and remove them:"""

# Visualizing outliers using boxplots
numerical_columns = ['Age', 'Fare', 'Room']  # Specify numerical columns to check for outliers
for column in numerical_columns:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x=df[column])
    plt.title(f'Boxplot of {column}')
    plt.show()

# Handling outliers by capping them
for column in numerical_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df[column] = np.where(df[column] < lower_bound, lower_bound, df[column])
    df[column] = np.where(df[column] > upper_bound, upper_bound, df[column])

numerical_columns = ['Age', 'Fare', 'Room']
for column in numerical_columns:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x=df[column])
    plt.title(f'Boxplot of {column}')
    plt.show()

"""-> As we can see there is no outlier in this numerical columns:"""

